### ISSUE TITLE
Tencent ncnn

### ISSUE THREAD

**Issue by eric612** [eric612/MobileNet-YOLO#10]
Currently using my old models (not all depthwise convolution), need upgrade mobilenet-yolov2 to mobilenet-yolov3

https://github.com/Tencent/ncnn/tree/master/benchmark

**Comment by nihui** [comment]
thanks for your awesome work !

**Comment by StephenLee2016** [comment]
你好，想请问下，mobilenet-yolov3在ncnn下支持吗？

**Comment by eric612** [comment]
https://github.com/Tencent/ncnn/pull/645
