### ISSUE TITLE
hanged when "creating layer data"

### ISSUE THREAD

**Issue by kuriel07** [eric612/MobileNet-YOLO#101]
Model : yolov3_lite

Backbone : mobilenet 

Questions : my training got hanged when "creating layer data", i tried to run the caffe train on jetsonTX2, i already prepared custom LMDB file (it works with other caffe, weiliu89), i changed the number of class to 12 on prototxt file (cannot ctrl+C the caffe, must kill it from system monitor), i only tried with mobilenet+yolov3_lite but haven't tried it with other models

Log files : 

[terminal_log.log](https://github.com/eric612/MobileNet-YOLO/files/3104156/terminal_log.log)
[mobilenet_yolov3_lite_train.prototxt.zip](https://github.com/eric612/MobileNet-YOLO/files/3104166/mobilenet_yolov3_lite_train.prototxt.zip)

**Comment by eric612** [comment]
I'm not sure the where is problem , but I you can try something to find out it 
* Set training input resolution to 320x320 , and prob set to 1 , kill others
* Try mobilenet-ssd or pelee-sdd on this project
* Add pre-trained weight when training

**Comment by kuriel07** [comment]
thanks for replying,

i'm currently debugging the program it seems that prefetch thread terminated suddenly, adding pre-trained data caused this issue (also the prob should at 0.5 using 320x320 input, when i set 1.0 it says the blob size didn't matched), also is it necessary to use pre-trained weight for training?

**Comment by kuriel07** [comment]
just solved the problem, 

i forgot that caffe cannot use the same lmdb file for test and train session
