### ISSUE TITLE
upsample in Mobilenet YOLOv3 coco

### ISSUE THREAD

**Issue by ryusaeba** [eric612/MobileNet-YOLO#103]
Hi @eric612 

For [Mobilenet YOLOv3 on coco](https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3_coco/mobilenet_yolov3_test.prototxt),

Output feature map size of conv15 is 1x1024x13x13. The next one is upsample layer. 
The upsample layer is using depth-wise deconvolution, correct? If so, why the convolution_param is not like below, since input feature map is 1x1024x13x13.
num_output: 1024
group: 1024

Is there something wrong?

Thanks,

**Comment by eric612** [comment]
Of course can set to 1024 , however you can see this performance [log](https://github.com/eric612/MobileNet-YOLO/blob/master/benchmark/test-416.log) , the deconvolution of  mobilenet yolov3 lite cost 1.38 ms , where I only set num_output=512 , and kernel_size = 1 , it is a bottleneck of inference speed in caffe

**Comment by ryusaeba** [comment]
For this case, input is 1x1024x13x13. 
If you are using depthwise deconv with 512 output channels, how does caffe handle the input feature map?

Does caffe perform same kernel twice? First time for 0-511x13x13. Second time for 512-1023x13x13?

**Comment by eric612** [comment]
You can refer this [example](https://blog.yani.io/filter-group-tutorial/) , the limitation was the input channel can be divide with group number . Actually , it it not depthwise convolution , and I did not use pointwise convolution also .

**Comment by ryusaeba** [comment]
Sorry, what I meant is separate convolution, i.e first convolution in depthwise convolution .
According to your answer, it seems not a separate convolution. I will take a look your example. 
Thanks

**Comment by ryusaeba** [comment]
Sorry, what I meant is separate convolution, i.e first convolution in depthwise convolution .
According to your answer, it is belonging to a group convolution which is introduced by alexnet.

Originally, I thought the group convolution is output channel should be divided by group number. 
So do you meant there has another limitation that is input channel should be also divided by group number?

**Comment by ryusaeba** [comment]
After checking more details, what I thought for group convolution is not correct. The limitation for group convolution is input channel should be divided by group number. 
Many thanks for your help.

**Comment by ryusaeba** [comment]
@eric612 
I have one more question about group de-convolution and group convolution.
For alexnet example, input feature map is 1x96x54x54. When I print the group=2 convolution kernel shape by using net.params[l.name][0].data.shape, it will be OUTPUT_CHANNELx48 (96/2) xHxW.
For mobilenet yolov3, input feature map is 1x1024x13x13. I will expect the group=512 deconvolution kernel shape is OUTPUT_CHANNELx2 (1024/512)xHxW. But when I print the shape, I don't see it. 
Do you have any idea about this?

**Comment by ryusaeba** [comment]
> Of course can set to 1024 , however , you can see this performance [log](https://github.com/eric612/MobileNet-YOLO/blob/master/benchmark/test-416.log) , the deconvolution layer of mobilenet-yolov3-lite cost 1.38 ms , where I only set num_output=512 , and kernel_size = 1 , it is a bottleneck of inference speed in caffe

According to this, if we are using 1024 as output channel, the inference speed will be much slower, correct?
