### ISSUE TITLE
what's the input dimension for anchors calculation?

### ISSUE THREAD

**Issue by lqian** [eric612/MobileNet-YOLO#106]
Model : yolov3-lite

Backbone : mobilenet 

Questions : in the VOC mobile-yolo-lite model, AnnotaionData layer defines many input dimension. which dimension should use to calculate anchors?

 

[yolov3.prototxt](https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_train.prototxt) for VOC

**Comment by eric612** [comment]
The default anchors was calculated from Coco dataset with resolution 416

Link Qian <notifications@github.com> 於 2019年4月27日 週六 下午1:57 寫道：
