### ISSUE TITLE
DepthwiseConvolution问题

### ISSUE THREAD

**Issue by wzj5133329** [eric612/MobileNet-YOLO#110]
你好，请问这个DepthwiseConvolution层使用CAFFE与普通的卷积层是不是一样的啊，就是普通的卷积层实现？另外为什么DepthwiseConvolution不需要添加进caffe.protoa啊?

**Comment by northeastsquare** [comment]
同意你的说法，https://github.com/eric612/MobileNet-YOLO/issues/127， 可以印证，这个depthwiseconvolution和普通卷积是一样的，加个group. 我在转运模型时候，报错，说depthswiseconvlution没有group参数，于是把group去掉，发现参数文件由20M一下到了170多兆，感觉不行，仔细琢磨这个depthwiseconvolution在干嘛，看了几个小时，发现不对，分组卷积不能有group参数。搜索到你的回答，和127issue, 再一对比普通卷积conv层发现是一样的，那么这里为什么要把普通卷积复制一遍，增加一个新名称的层，而且名实不符，dwconvolution, 实际是group等于输入通道数的分组卷积。@eric612

**Comment by northeastsquare** [comment]
please reopen this issue

**Comment by eric612** [comment]
當group 與 channel 相等時， 兩邊的結果會是一樣的，但[Depthwise Convolution](https://github.com/yonghenglh6/DepthwiseConvolution) 速度會快上許多，尤其是在訓練時，不妨可以試試，另外Caffe 實作Depthwise convolution 的方式有好幾種，例如[Convolution Depthwise](https://github.com/BVLC/caffe/pull/5665/files)，在Github 都可以搜尋的到。

**Comment by northeastsquare** [comment]
哦，这样啊，谢谢您的解答
