### ISSUE TITLE
如何加入关键点回归

### ISSUE THREAD

**Issue by wait1988** [eric612/MobileNet-YOLO#118]
你好，对caffe不是很熟，想请教下，如果做类似人脸关键点的任务，既回归边框，又回归点，要改那些东西呢？

**Comment by eric612** [comment]
不太確定你要的是哪種Loss ，但Caffe目前也有一些做人臉的專案，如：
https://github.com/CongWeilin/mtcnn-caffe/blob/master/48net/train48.prototxt

後面的bounding box可以用SSD 或YOLO 等detector取代，但我實際上沒有做過，所以不確定是不是你需要的

**Comment by wait1988** [comment]
你给的这个链接不错，我试试看
