### ISSUE TITLE
segmentation + object detection + lane detection

### ISSUE THREAD

**Issue by iunknown10** [eric612/MobileNet-YOLO#126]
Hi eric,
跑了你的 Pelee + SSD + driverable maps模型，效果不错，如果把车道线也加进去，具体应该怎么做？

**Comment by iunknown10** [comment]
labelmap.prototxt添加一个车道线的类，对应的driverable map重新生成带车道线的，能否行得通？
item {
  name: "LaneLine"
  label: 3
  label_id: 3
  r: 255
  g: 255
  b: 255
}

**Comment by eric612** [comment]
理論上可行，但實際上需要花蠻多時間修改，原因在於bdd100k的land marking資料是存在json裡，與tsimple一樣，必須將點座標取出再畫到圖上

**Comment by iunknown10** [comment]
这个我可以搞定（我先开始处理数据),网络部分不需要调整吧？(碰到问题再来问） 多谢！

**Comment by eric612** [comment]
是的 網路部分只要修改seg conv 的channel數(=class 數目)

**Comment by iunknown10** [comment]
模型训练出来了，我想让模型在Pelee-Seg-TensorRT下跑起来，caffemodel用[https://github.com/chuanqi305/MobileNet-SSD/blob/master/merge_bn.py](url)转了，prototxt直接用的pelee_deploy_iplugin.prototxt。跑出来有很多错误的目标框，是什么原因呢，应该修改什么地方？ 多谢！

**Comment by eric612** [comment]
那個連結轉其他model會有些問題，我是用這個連結
https://github.com/Robert-JunWang/Pelee/blob/master/tools/gen_merged_model.py

**Comment by iunknown10** [comment]
可以了 :)  多谢！

**Comment by yiboliu31** [comment]
@iunknown10 老哥你好，本人最近也在折腾bdd100k 车道线这部分，请问老哥是怎么处理的
