### ISSUE TITLE
[Training Issue] Inference "mobilenet_yolov3_lite_deploy.caffemodel" to TX2 

### ISSUE THREAD

**Issue by Starlightfalls** [eric612/MobileNet-YOLO#127]
Model : mobilenet_yolov3_lite

Backbone : mobilenet 

Questions :
I trained with my dataset using 'model/yolov3/mobilenet_yolov3_lite_solver.prototxt'.
I think, training is successful because my learning pc is well detect objects of it.
So to inference a trained '.caffemodel' file from NVIDIA TX2, use 'examples/merge_bn/convert_deploy.py' file with '.caffemodel' and 'bn_deploy.prototxt file'.
However, TX2 has an Error message that it can not be used because there is no DepthwiseConvolution Layer.

I was able to inference and detect objects using [mobilenet-yolov3-lite model] in advance.(https://github.com/eric612/TensorRT-Yolov3-models/tree/master/mobilenet-yolov3-lite)

How do i inference mobilenet_yolov3_lite network into TX2 ??

Log files : -

Other : 
TX2(Jetson 4.) & TensorRT 5.0.6

**Comment by eric612** [comment]
It is recommend to try non merged bn model first 

- You can reference this deploy [model](https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_bn_deploy.prototxt) 

-  Use editor to replace layer type "DepthwiseConvolution" be "Convolution" 

- Change the input data layer and output layer like this [prototxt](https://github.com/eric612/TensorRT-Yolov3-models/blob/master/mobilenet-yolov3-lite/mobilenet_yolov3_lite_deploy.prototxt)

- Then you can try merge batchnorm step and follow the same steps

**Comment by Starlightfalls** [comment]
@eric612 Thanks for your reply.
I tried your method.
But, Error occurred in 'merge batchnorm python'.
Perhaps there is no information of yolo-det output layer.

So, i change only input data layer and replace  "DepthwiseConvolution" to "Convolution".
The inference succeeded in TX2 but the detection was rare.

Is there another solution?
Or do you know how to install TensorRT 5.1.x ver. in Jetpack4.2 ??

**Comment by eric612** [comment]
Would you mind to upload your caffemodel and prototxt , ans also converted tensorrt prototxt and caffmodel ?

**Comment by Starlightfalls** [comment]
I uploaded [here](https://drive.google.com/drive/folders/1KI6ISg7rNo7FVON5c3fXw-qTr8zYhQLV?usp=sharing)

The number of class is 15.
'mobilenet_yolov3_lite_bn_deploy.prototxt' file is a changed input data layer and "DepthwiseConvolution" to "Convolution".

And when i interence in TX2, i change the output layer of 'merged.prototxt' file from 'Yolov3DetectionOutput' type to 'Yolo' type.

**Comment by eric612** [comment]
Hi Starlightfalls , 
You can skip convert_deploy.py this step , it is only increase inference speed , so you can keep the batchnorm and scale layer , and just inference in tx2 , remember to change layer type and output layer blobs names.

**Comment by Starlightfalls** [comment]
@eric612 Thanks for your apply.
The inference succeeded in TX2 with 'mobilenet_yolov3_lite_bn_deploy.prototxt' and 'mobilenet_yolov3_lite_deploy_iter_13000.caffemodel'.
Executing 'MobileNet-YOLO/demo_yolo_lite.sh' file on training-PC is pretty high detection, but it is too low on tx2.

Is there way to increase the detection rate in TX2 ??

**Comment by Starlightfalls** [comment]
@eric612 
Thank you for your help.
I think this problem is due to image pre-processing.
I revised the code in TX2 based on the [this](https://github.com/eric612/MobileNet-YOLO/blob/master/examples/yolo/yolo_detect.cpp), and the detection rate increased. 
Thanks again for the help :) :+1:
