### ISSUE TITLE
Hi, have you compared your mobileNet-yolov3 with the original yolov3-tiny in speed and precision?

### ISSUE THREAD

**Issue by zhangjinsong3** [eric612/MobileNet-YOLO#13]
As titled, I want to train my data in yolov3 and i find it a little slow of yolov3. Thus, I trained yolov3-tiny but it works not very well. So I want to know if the version of yolov3 with the mobilenet backend perform better than yolov3-tiny?

**Comment by eric612** [comment]
Not yet , but I will add coco training result and compare with original yolov3 (also include tiny version) in the future. Please keep in mind.

**Comment by zhangjinsong3** [comment]
@eric612 Another question.In your mobilenet_yolov3_train.prototxt, the Yolov3Loss3 layer has a param of side:26,why not 52 in 3rd yolo layer as the darknet is ?

**Comment by zhangjinsong3** [comment]
@eric612  Thanks very much for  your awesome work！

**Comment by eric612** [comment]
Update mobilenet-yolov3 coco mAP
