### ISSUE TITLE
Issue using the model with opencv

### ISSUE THREAD

**Issue by yuangreg** [eric612/MobileNet-YOLO#16]
Hi, 
I downloaded your model, i.e., mobilenet_yolov3_lite_deploy.caffemodel and mobilenet_yolov3_lite_deploy.prototxt, and use the opencv package for testing, which is given as follows.
https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py.

The following issue comes up. 
error: (-2:Unspecified error) Can't create layer "detection_out" of type "Yolov3DetectionOutput" in function 'getLayerInstance'

I have tried other caffe models from github, and they all works fine under this opencv tool.

Could you please help on this?

**Comment by eric612** [comment]
Yolov3DetectionOutput were my custom define layer , If you want use it in opencv , you need miragrate code and compile it first. Or you can try the converted darknet-yolov3 model  first .

**Comment by mv2050arshad** [comment]
> 
> 
> Hi,
> I downloaded your model, i.e., mobilenet_yolov3_lite_deploy.caffemodel and mobilenet_yolov3_lite_deploy.prototxt, and use the opencv package for testing, which is given as follows.
> https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py.
> 
> The following issue comes up.
> error: (-2:Unspecified error) Can't create layer "detection_out" of type "Yolov3DetectionOutput" in function 'getLayerInstance'
> 
> I have tried other caffe models from github, and they all works fine under this opencv tool.
> 
> Could you please help on this?

Hi. could you successful to solve this issue?
