### ISSUE TITLE
Should I include “background” class, when I  modify labelmap_voc.prototxt to train yolov3_lite[Training Issue]

### ISSUE THREAD

**Issue by GitEasonXu** [eric612/MobileNet-YOLO#166]
Model : yolov3-lite

Backbone : mobilenet 

Questions :
It is well known that the training process of yolov3 is not include `background` class for `num_output` is (5+classes)*3. If I have 5 classes (for eg: car, bus, motorcycle, bicycle, truck), `num_output` is (5+5)*3=30. 
But the `num_output` is (5+6)*3=33 not equals 30, if I include "background" class when I modify `labelmap_voc.prototxt` as shown below:
```
item {
  name: "none_of_the_above"
  label: 0
  display_name: "background"
}
item {
  name: "car"
  label: 1
  display_name: "car"
}
item {
  name: "bus"
  label: 2
  display_name: "bus"
}
item {
  name: "motorcycle"
  label: 3
  display_name: "motorcycle"
}
item {
  name: "bicycle"
  label: 4
  display_name: "bicycle"
}
item {
  name: "truck"
  label: 5
  display_name: "truck"
}
```
I refer to this[README](https://github.com/PiyalGeorge/MobileNet-YOLO/tree/master/models/yolov3)

**Comment by MuhammadAsadJaved** [comment]
You do not need to include Background for the calculation of num_output.     It must be according to the formula you mentioned.  (5+num_classes) x 3.

**Comment by GitEasonXu** [comment]
@MuhammadAsadJaved 
Should I add `background` class to `labelmap_voc.prototxt`, when I modify `labelmap_voc.prototxt`.   

If I add  `background` class to `labelmap_voc.prototxt`, the `num_output`(5+num_classes)*3 of `yolov3` is different from `num_class`(5+num_classes+1)*3 of `labelmap_voc.prototxt` .

**Comment by MuhammadAsadJaved** [comment]
1-yes you can not remove background class  which is label 0 in labelmap_voc.prototxt. 

2-when you calculate the num_output we do not consider background in the formula .  

so for your case num_class is 5 , just change the num_output: 30.     do not worry about number of classes difference in lablmap_voc.prototxt. and in actual.  for more details check this link. 

https://github.com/PiyalGeorge/MobileNet-YOLO/tree/master/models/yolov3

**Comment by GitEasonXu** [comment]
@MuhammadAsadJaved 
OK, thank you so much!
