### ISSUE TITLE
Conversion of caffe weights to darknet format 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [eric612/MobileNet-YOLO#168]
Hi, @eric612 
    The current repo can not use for retraining caffe model for different number of classes , for example current weights are about 80 classes if I want to retrain the model using these weights for 2 classes, it shows some shape mismatch error. 

So one idea is convert to these caffe weights to darknet format and then train the darknet , after training again convert darknet weights to caffe format and use them.  

So my question is how to convert these caffe weights to darknet format? 

Is there any tool or link?

**Comment by eric612** [comment]
Follow this step , I think you meet the error was layer name and channel conflicts . you can just change the name to a new name like  yolo/conv5 to yolo/conv5/new/

**Comment by MuhammadAsadJaved** [comment]
Thank you @eric612  I found the solution. I was following the same steps mentioned on the given link. But there was the error. Now i have changed the layers name and it starts training. but I am afraid it will train the model from scratch as it was mentioned in the error.   Will it start from scratch or used the pre-trained weights if i renamed the layers?
