### ISSUE TITLE
[Bug] Strange inference time

### ISSUE THREAD

**Issue by nvnnghia** [eric612/MobileNet-YOLO#172]
**Describe the bug**
The inference time is not consistent. At the first few frames, the inference time is around 18-20 ms. however this inference time slightly increase, at frame ~4000 the inference time per frame is around 400 ms. at frame ~6000 the inference time is around ~650ms. 

**To Reproduce**
sh scripts/train_pelee_ssd_bdd100k.sh

**Expected behavior**
I think the processing time should not be too much different.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - GPU:  RTX 2080

**Additional context**
Is this consider a bug? any comment on this? Thank you

**Comment by eric612** [comment]
Did you log the gpu ram usage ?

**Comment by nvnnghia** [comment]
It was my mistake. Sorry. Closing this issue now.
