### ISSUE TITLE
[Training Issue] conv26层的ｎｕｍ_ｏｕｔｐｕｔ 是什么意思？

### ISSUE THREAD

**Issue by BaofengZan** [eric612/MobileNet-YOLO#193]
Model : segmentaion

Backbone : mobilenet 

Questions : 

在cityscapes中自带的ｔｒａｉｎ.ptototxt中ｃｏｎｖ２６中　“num_output: 19 # channel = class number”
这里的１９代表什么？

谢谢！

**Comment by eric612** [comment]
Segmentation 要分辨的種類，Cityscapes預設是19種

**Comment by BaofengZan** [comment]
＠ｅｒｉｃ612 谢谢回复，我也刚好搜索到了其他的解释，已经明白了。非常感谢
