### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".

### ISSUE THREAD

**Issue by milosgajdos83** [eric612/MobileNet-YOLO#20]
When trying to converty `yolov3-tiny` model I encounter the folllowing error:

```
# python darknet2caffe.py yolov3-tiny.cfg yolov3-tiny.weights tiny-yolov3.prototxt yolov3-tiny.caffemodel
Traceback (most recent call last):
  File "darknet2caffe.py", line 500, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 10, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "darknet2caffe.py", line 111, in cfg2prototxt
    blocks = parse_cfg(cfgfile)
  File "/temp/MobileNet-YOLO/models/darknet_yolov3/cfg.py", line 27, in parse_cfg
    key,value = line.split('=')
ValueError: need more than 1 value to unpack
```

When I try to build `yolov3` the convert script crashes with different error:

```
# python darknet2caffe.py yolov3.cfg yolov3.weights yolov3.prototxt yolov3.caffemodel
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 4118:35: Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1003 19:31:44.715860 15696 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: yolov3.prototxt
*** Check failure stack trace: ***
Aborted
```

Any ideas how to fix this? Thanks.

**Comment by shuxiao9058** [comment]
you should implement the user defined layer yourself.

**Comment by milosgajdos83** [comment]
Which user defined layer? Sorry, I'm a bit confused.

**Comment by le-lshr1214** [comment]
@milosgajdos83 @shuxiao9058  
How to fix this error?

**Comment by le-lshr1214** [comment]
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 4118:35: Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1012 16:57:21.913152 15883 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file:

**Comment by PiyalGeorge** [comment]
@milosgajdos83 @shuxiao9058  
how did you fix this?

**Comment by eric612** [comment]
Unmark and modify darkner2caffe.py
sys.path.append('path to your MobileNet-YOLO caffe root')

**Comment by PiyalGeorge** [comment]
@eric612 Tried that, but still getting same error -
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 732:35: Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1015 15:32:59.454461 17254 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /media/vkchcp0013/mstu_hpat/ZFGG_PRSC/yolo-to-caffe/converted/tiny-yolov3.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by eric612** [comment]
I just update a new version which fixed the python path , you can try following step :
1. Git pull to newest version 
2. Follow the build step , do not miss make pycaffe
3. try again

**Comment by 18hfliu** [comment]
> Unmark and modify darkner2caffe.py
> sys.path.append('path to your MobileNet-YOLO')

why cann't use caffe itself executeable file upgrade_net_proto_text convert old caffe mobilenet_yolov3_lite_deploy.prototxt to caffe2 file?
