### ISSUE TITLE
[Compile error ] src/caffe/layers/yolov3_detection_output_layer.cu(12): error

### ISSUE THREAD

**Issue by Rahn80643** [eric612/MobileNet-YOLO#203]
Hi,
When I compiled the project, I met the error message: src/caffe/layers/yolov3_detection_output_layer.cu(12): error: identifier "gaussian_box_" is undefined.

I followed the tutorials in wiki to compile my project, and the attachments are my Makefile.config and Makefile .

![20191108_error_mobilenet-YOLO](https://user-images.githubusercontent.com/8951991/68479546-8ab48a80-026d-11ea-8f2e-c8e37d1fc173.png)
[Makefile.config.txt](https://github.com/eric612/MobileNet-YOLO/files/3824735/Makefile.config.txt)
[Makefile.txt](https://github.com/eric612/MobileNet-YOLO/files/3824736/Makefile.txt)
![20191108_error_mobilenet-YOLO](https://user-images.githubusercontent.com/8951991/68479665-d830f780-026d-11ea-8e2e-b8a5701a42c3.png)

**Comment by eric612** [comment]
Update

**Comment by Rahn80643** [comment]
@eric612 : Thank you for the update, now the cloned project can be compiled.
