### ISSUE TITLE
[Training Issue]请教，训练时如何加入负样本来降误检，如何修改。

### ISSUE THREAD

**Issue by wltext** [eric612/MobileNet-YOLO#206]
直接加入误检图和空xml，生成lmdb吗？

**Comment by eric612** [comment]
可以的

**Comment by yyqgood** [comment]
@wltext 你这种方式有降低误检吗？

**Comment by yyqgood** [comment]
@eric612 试了下你说的；在create_data时会出错

**Comment by eric612** [comment]
@yyqgood 空的xml 還是要有檔頭 ，只是不加object 
![image](https://user-images.githubusercontent.com/15793472/99748814-31d23000-2b18-11eb-87c1-7e89797b6e5c.png)

**Comment by yyqgood** [comment]
@eric612 多谢你的回复；我将实际训练下

**Comment by yyqgood** [comment]
@eric612 我使用你说的方式，训练了负样本；之后测试确实很好的降低了误检。谢谢！

**Comment by yyqgood** [comment]
@wltext 可以关issues了？
