### ISSUE TITLE
[Training Issue] 训练cityscape segmentation时，loss的几个问题

### ISSUE THREAD

**Issue by BaofengZan** [eric612/MobileNet-YOLO#207]
作者你好，我在训练cityscape segmentation时，在你提供的训练模型上微调，但是loss降到20后，就开始小范围震荡，另外yolov3_layer.cpp输出的 obj信息一直小于0.5。 但是yolo_seg.cpp 的obj一直保持在0.8。 这样的现象是正常的么？  或者说是我的预训练模型使用的不对？

**Comment by eric612** [comment]
建議將model跟log檔案上傳，我才有比較多的資訊可以判斷，類似下列連結
https://github.com/eric612/MobileNet-YOLO/issues/205

**Comment by BaofengZan** [comment]
@eric612 您好，我之前训练没有保存log信息。我拍了照片，您看一下。 我后面再次训练下，保存个log日志。

![webwxgetmsgimg](https://user-images.githubusercontent.com/20653176/68822425-d763ef80-06cb-11ea-9f9d-1a8b887795fe.jpg)

另外我是移植到windows下训练。

 train.prototxt和test.prototxt以及solver.proto 都是和/models/cityscapes/文件夹下的一样，仅仅修改了数据路径。

其次。数据我使用了您提供的CityPersonOnRoad数据。 并且将修改了create_list.sh
，将35行修改为 "sed -i s/$/_gt_Fine_labelIds.png/g” %label_files2 "。

下面是生成数据的一些脚本。
[create_data.sh](https://github.com/eric612/MobileNet-YOLO/files/3844393/create_data.sh.txt)
[create_list.sh](https://github.com/eric612/MobileNet-YOLO/files/3844394/create_list.sh.txt)
[train.txt](https://github.com/eric612/MobileNet-YOLO/files/3844396/train.txt)
[val.txt](https://github.com/eric612/MobileNet-YOLO/files/3844397/val.txt)

**Comment by BaofengZan** [comment]
@

**Comment by BaofengZan** [comment]
@

**Comment by BaofengZan** [comment]
@eric612 , 作者您好，我简单训练了一下，这里是log， 我感觉里面输出的信息不正确（也有可能是我训练的次数太少）。 希望您能从里面找到一些问题，谢谢 

[log.log](https://github.com/eric612/MobileNet-YOLO/files/3845066/log.log)

**Comment by eric612** [comment]
imagenet_mb_v2_t4_iter_500000 裡面的layer 跟你使用的model應該是不一樣的? 看起來weighting沒有讀進去
![image](https://user-images.githubusercontent.com/15793472/68835573-528ccc00-06f3-11ea-95b6-59d9b3dea7fa.png)

**Comment by BaofengZan** [comment]
@eric612 我没有理解“用object detection 的pretrain weights不會比較好”这句话的意思，使用能否再解释一下？  我的预训练模型如果使用 您里面提供的[https://github.com/eric612/MobileNet-YOLO/wiki](wiki)，是否可行？还是使用其他的？

**Comment by eric612** [comment]
mobilenetv1 你可以使用這個
https://drive.google.com/file/d/0B3gersZ2cHIxZi13UWF0OXBsZzA/view

**Comment by BaofengZan** [comment]
@eric612  好的。谢谢您。我继续训练下模型。

**Comment by BaofengZan** [comment]
@eric612  谢谢，已经出现分割效果。十分感谢！！！！
