### ISSUE TITLE
[Training Issue]（segmentation）BN层的use_global_stats参数设置问题？

### ISSUE THREAD

**Issue by BaofengZan** [eric612/MobileNet-YOLO#209]
作者你好，在训练分割任务时，对比了 train.prototxt和text.ptototxt，发现BN层设置是一样 。但是按照理论，训练的时候，要将BN层中use_global_stats设置为false，而测试的时候将use_global_stats设置为true。 而在caffe.proto中的 use_global_stats默认值是1，因此我有一个疑问：这样的设置理论会对训练有影响，但是我训练出来的模型还是可以检测以及分割出物体的，这里有什么其他的解释么？

**Comment by eric612** [comment]
https://github.com/eric612/MobileNet-YOLO/blob/master/src/caffe/layers/batch_norm_layer.cpp#L14

**Comment by BaofengZan** [comment]
@eric612  感谢，我没有看源码。 是我的疏忽。

**Comment by BaofengZan** [comment]
@eric612  我还有个问题请教下。 https://github.com/eric612/MobileNet-YOLO/blob/9e32643b55399b914f7b3ab7d0f9f5a092a7002c/data/cityscapes/labelmap_seg.prototxt#L173 这个label_id 应该是要分割的id，但是在实际测试中，只能分割中 人(label_id=1)以及 路(label_id=2)，这可能给是什么原因？ 谢谢
