### ISSUE TITLE
[Bug]【Segmentation】 Yolo_detect.cpp 和 detect_and_seg.py结果不一致.

### ISSUE THREAD

**Issue by BaofengZan** [eric612/MobileNet-YOLO#211]
**Describe the bug**
@eric612 作者你好，我在前向测试时发现几个有趣的问题：

1 首先是分割任务上，我使用 [wiki](https://github.com/eric612/MobileNet-YOLO/tree/master/data/cityscapes)的测试脚本，使用py文件前向， 检测结果和分割结果都可以正常显示，

2 但是使用和（1）相同的caffemodel和deploy， Yolo_detect.cpp前向时， 就没有结果，debug发现，在net_->forward()时，检测输出层一直为[0, -1,-1,-1,-1,-1,-1]。

3为了排除是代码的问题， 我又使用model/yolov3下的caffemodel和deploy进行测试Yolo_detect.cpp，检测结果就正常。

现在这三个结果产生了矛盾，所以请求作者给予帮助！

**Comment by wweiCV** [comment]
When I use yolo_detect.cpp to detect, the output is always [0, -1, -1, -1, -1, -1, -1]. How can I modify it? Ask for your help!

**Comment by BaofengZan** [comment]
@wweiCV 看一下 #213
