### ISSUE TITLE
[Bug] 数据读入层归一化bug说明。

### ISSUE THREAD

**Issue by BaofengZan** [eric612/MobileNet-YOLO#213]
https://github.com/eric612/MobileNet-YOLO/blob/9e32643b55399b914f7b3ab7d0f9f5a092a7002c/src/caffe/data_transformer.cpp#L629

@eric612 作者你好，您在这里由于将归一化写死了。 而在yolo_detect.cpp中做图像归一化时，没有 除以255，并且train.prototxt中的transform_param中的sacle为1/127.5， 会对我们造成混淆，因此在Segmentation任务前向时，没有输出结果  如问题 #199 #211。

**Comment by eric612** [comment]
由於時間太久了，記憶有點模糊，但應該不是你說得這樣，既然你用的是VC，應該可以使用單步追蹤trace ，或是把圖打印出來。

Scale的參數會用在這行
https://github.com/eric612/MobileNet-YOLO/blob/master/src/caffe/layers/annotated_data_layer.cpp#L371

你說的這行，會寫死成1/255是因為我前面是設segmentation gt map的值是255
https://github.com/eric612/MobileNet-YOLO/blob/master/src/caffe/layers/annotated_data_layer.cpp#L494

https://github.com/eric612/MobileNet-YOLO/blob/master/src/caffe/layers/annotated_data_layer.cpp#L446

**Comment by BaofengZan** [comment]
@eric612  感谢回复。 我看了下代码，好像正如您所说的那样。   对于原图的归一化处理还是利用train.prorotxt中的参数，对seg gt 是二值图像。 

另外我在测试分割任务时，使用cpp推理， 归一化操作减去了均值【127,5， 127.5， 127.5】， 但是没有除以255， 就没有检测以及分割结果。  如果加上这一步骤，就可以正常显示结果。 

其次，我如果将均值全部设置为0， 并且有除以255的操作， 在同一张图上的分割结果 效果还会有所提升。

这里我很迷惑， 我会继续追踪代码。

**Comment by didibaba** [comment]
@BaofengZan 我使用script中的demo_cityscape脚本没有得到正确的推理，是要修改地方吗？

**Comment by BaofengZan** [comment]
@didibaba  具体输出的信息是什么呢？ 是结果不正确还是没有任何结果？
