### ISSUE TITLE
关于mobilenetv2作backbone的yolo

### ISSUE THREAD

**Issue by smallhaolzh** [eric612/MobileNet-YOLO#239]
我看了mobilenetv2-yolov3-lite的train.prototxt的网络结构，发现作者的在mobilenetv2是直接接了一些Depthwise Convolution，如果直接接全连接网络是否也有效？这里关于后接网络的选择，请问有什么建议吗？因为查看过一些yolo在不同backbone上的网络结构，发现都各有异同。

**Comment by eric612** [comment]
這裡的模型大部分是我個人的經驗所建構，而我盡量都是以能在硬體上的效率為優先考量，這些都不是原始作者或是一些知名的公司提供，建議只能參考，要怎麼設計你可以多參考一些專案

**Comment by smallhaolzh** [comment]
> 這裡的模型大部分是我個人的經驗所建構，而我盡量都是以能在硬體上的效率為優先考量，這些都不是原始作者或是一些知名的公司提供，建議只能參考，要怎麼設計你可以多參考一些專案

Thanks.
