### ISSUE TITLE
How to save the predicted image in the deploy phase?

### ISSUE THREAD

**Issue by zpge** [eric612/MobileNet-YOLO#242]
As the title, I want to save the predicted result in disk.

**Comment by MuhammadAsadJaved** [comment]
@zpge  I have the same problem. Have you resolved it?  As I saw in the code , there is code to save the output but do not know why it is not working, 

https://github.com/eric612/MobileNet-YOLO/blob/master/examples/ssd/ssd_detect.cpp#L445

**Comment by zpge** [comment]
> @zpge I have the same problem. Have you resolved it? As I saw in the code , there is code to save the output but do not know why it is not working,
> 
> https://github.com/eric612/MobileNet-YOLO/blob/master/examples/ssd/ssd_detect.cpp#L445

You can use the scripts in example/yolo/detect.py

**Comment by MuhammadAsadJaved** [comment]
@zpge  Yes i found that solution but unfortunately, results are different if we detect using detect.py and using demo_darknet_yolov3.sh  . The results are better with shell.

**Comment by zpge** [comment]
> @zpge Yes i found that solution but unfortunately, results are different if we detect using detect.py and using demo_darknet_yolov3.sh . The results are better with shell.

I did not noticed that and have no clue on it.
