### ISSUE TITLE
VOC预训练模型

### ISSUE THREAD

**Issue by yyqgood** [eric612/MobileNet-YOLO#245]
你好，是否提供了VOC的预训练mobilenet yolov3 lite模型？就像COCO的预训练模型mobilenet_yolov3_lite_coco.caffemodel一样。
期待你的回复，谢谢！

**Comment by applefishsky009** [comment]
期待回复，复现mobilenet yolov3 lite在VOC上的训练过程，mAP只有71，没有达到76.3。
我用单张2080TI，将batch size改为了3， iter_size改为21以尽可能接近原训练过程。

**Comment by eric612** [comment]
因為時間有點久遠了，你們試試看這個[weights](https://drive.google.com/file/d/1PMbPnJ0fIPBzq3NMS6m3y8DFLbJlpvaz/view?usp=sharing)，不行再跟我說，因為這兩年之間，前處裡與loss變動幅度較大，可以使用舊版的code來復現

**Comment by applefishsky009** [comment]
> 因為時間有點久遠了，你們試試看這個[weights](https://drive.google.com/file/d/1PMbPnJ0fIPBzq3NMS6m3y8DFLbJlpvaz/view?usp=sharing)，不行再跟我說，因為這兩年之間，前處裡與loss變動幅度較大，可以使用舊版的code來復現

非常感谢你的解答，但这个链接需要权限访问，我已经申请访问权限，并期待您的回复。

**Comment by eric612** [comment]
我剛剛把權限設定成所有人都能訪問了
https://drive.google.com/file/d/1PMbPnJ0fIPBzq3NMS6m3y8DFLbJlpvaz/view?usp=sharing

**Comment by applefishsky009** [comment]
> 我剛剛把權限設定成所有人都能訪問了
> https://drive.google.com/file/d/1PMbPnJ0fIPBzq3NMS6m3y8DFLbJlpvaz/view?usp=sharing

O(∩_∩)O谢谢，已经可以下载到了。有结果我会反馈的。

**Comment by yyqgood** [comment]
@applefishsky009 你在做什么项目呢?

**Comment by KelvinHuang666** [comment]
can u support me yolov3.caffemodel as pretrain-model???

**Comment by applefishsky009** [comment]
> @applefishsky009 你在做什么项目呢?

硬件加速相关的项目。需要在各个算法上验证。后来由于资源原因，我没有纠结这个模型性能了，而是直接用来做效率测试，使用其他模型做性能测试。
