### ISSUE TITLE
yolov3-tiny loss layer setting

### ISSUE THREAD

**Issue by wzjiang** [eric612/MobileNet-YOLO#27]
hello，I have pretrained a tiny yolo in imagenet. And I have looked your  yolov3-tiny.prototxt(it only have the Yolov3DetectionOutput layer). But I down't how to modified it to a train.prototxt. Could you give a train.prototxt, thank you very much(I tried a long time but it did't work)
 layer {
  name: "Yolov3Loss2"
  type: "Yolov3"
  bottom: "conv23"
  bottom: "label"
  top: "det_loss2"
  loss_weight: 1
  yolov3_param {
    side: 26
    num_class: 80
    num: 3  
    object_scale: 5.0
    noobject_scale: 1.0
    class_scale: 1.0
    coord_scale: 1.0
    thresh: 0.7
	anchors_scale : 16
	
	#10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
	
    biases: 10
    biases: 13
    biases: 16
    biases: 30
    biases: 33
    biases: 23
    biases: 30
    biases: 61
    biases: 62
    biases: 45
	biases: 59
    biases: 119
	biases: 116
    biases: 90
    biases: 156
    biases: 198
	biases: 373
    biases: 326
	
	mask:3
	mask:4
	mask:5
  }
}

**Comment by wzjiang** [comment]
And what is the different from coco and voc（such as voc）

**Comment by eric612** [comment]
[voc](https://drive.google.com/open?id=1RqiYrPvophkv72KNKdPkkcGEz5yqattv)

It means different dataset 

voc : 20 classes
coco : 80 classes

**Comment by wzjiang** [comment]
thank you very. I tried again. you help me a lot.
