### ISSUE TITLE
希望可以分享一下darknet-yolov3的模型，感谢！

### ISSUE THREAD

**Issue by TccccD** [eric612/MobileNet-YOLO#274]
yolov3 的 https://drive.google.com/file/d/17b5wsR9tzbdrRnyL_iFEvofJ8jCmQ1ff/view?usp=sharing
和
yolov3-spp 的 https://drive.google.com/file/d/12nLE6GtmwZxDiulwdEmB3Ovj5xx18Nnh/view?usp=sharing
失效了，请问可以重新共享一下吗，感谢！

**Comment by eric612** [comment]
剛剛修正並且commit了，你再測試一下

**Comment by TccccD** [comment]
> 剛剛修正並且commit了，你再測試一下

还是不行

**Comment by TccccD** [comment]
> 剛剛修正並且commit了，你再測試一下

链接应该是对了，没有权限访问

**Comment by eric612** [comment]
Updated , please try again

**Comment by TccccD** [comment]
> Updated , please try again

可以下载了，但是我看到模型的名字里带iter-1000，是1000个steps的spp-yolov3就能达到59吗

**Comment by eric612** [comment]
可以看[這裡](https://github.com/eric612/MobileNet-YOLO/tree/master/models/darknet_yolov3)

**Comment by TccccD** [comment]
非常感谢！
