### ISSUE TITLE
mobilenet_yolov3 training my own datasets

### ISSUE THREAD

**Issue by gllspeed** [eric612/MobileNet-YOLO#30]
I1107 07:01:37.377594  8360 net.cpp:84] Creating Layer Yolov3Loss1
I1107 07:01:37.377600  8360 net.cpp:406] Yolov3Loss1 <- conv23
I1107 07:01:37.377614  8360 net.cpp:406] Yolov3Loss1 <- label_data_1_split_0
I1107 07:01:37.377624  8360 net.cpp:380] Yolov3Loss1 -> det_loss1
F1107 07:01:37.377657  8360 yolov3_layer.cpp:143] Check failed: input_count == tmp_input_count (27075 vs. 9747) 
*** Check failure stack trace: ***
    @     0x7f4869f1e5cd  google::LogMessage::Fail()
    @     0x7f4869f20433  google::LogMessage::SendToLog()
    @     0x7f4869f1e15b  google::LogMessage::Flush()
    @     0x7f4869f20e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f486a6be242  caffe::Yolov3Layer<>::LayerSetUp()
    @     0x7f486a57432c  caffe::Net<>::Init()
    @     0x7f486a576b7e  caffe::Net<>::Net()
    @     0x7f486a4d03fa  caffe::Solver<>::InitTrainNet()
    @     0x7f486a4d19c5  caffe::Solver<>::Init()
    @     0x7f486a4d1cdf  caffe::Solver<>::Solver()
    @     0x7f486a716b11  caffe::Creator_SGDSolver<>()
    @           0x40be13  train()
    @           0x4084d0  main
    @     0x7f4868e2c830  __libc_start_main
    @           0x408cf9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by eric612** [comment]
See wiki
