### ISSUE TITLE
the detection problem

### ISSUE THREAD

**Issue by yinnxinn** [eric612/MobileNet-YOLO#35]
i use the yolov3_detection out type and get the result [0, -1, -1, -1, -1, -1] . have anyone met this problem??

**Comment by denti** [comment]
@yinnxinn hi! I have the same problem. I’m training from scratch. Loss decrease, but prediction gives [0, -1, -1, -1, -1, -1].
What was your problem?

**Comment by yinnxinn** [comment]
the pred

> @yinnxinn hi! I have the same problem. I’m training from scratch. Loss decrease, but prediction gives [0, -1, -1, -1, -1, -1].
> What was your problem?

try to decrease the threshold to check if there is some change in your prediction .

**Comment by FredHuang16** [comment]
Same problem!  Did you fix it?

**Comment by wweiCV** [comment]
@yinnxinn @FredHuang16 @denti  I meet same problem! This problem has troubled me for many days. How do you solve it?
