### ISSUE TITLE
框定位不准原因

### ISSUE THREAD

**Issue by jijiangyan** [eric612/MobileNet-YOLO#39]
你好，我用您的yolov3训练车牌检测，车牌大致都可以定位成功，但是框的并不是很精准，不知道有什么可以改进的方法？希望您能够提出一些建议！非常感谢

**Comment by lironghua318** [comment]
貌似作者在论文中有提到这个问题
However, when we look at the “old” detection metric of
mAP at IOU= .5 (or AP 50 in the chart) YOLOv3 is very
strong. It is almost on par with RetinaNet and far above
the SSD variants. This indicates that YOLOv3 is a very
strong detector that excels at producing decent boxes for ob-
jects. However, performance drops significantly as the IOU
threshold increases indicating YOLOv3 struggles to get the
boxes perfectly aligned with the object.

**Comment by jijiangyan** [comment]
也就是说这个定位精准不了是yolov3算法的瓶颈么？我发现训练车牌定位的loss值降到0.15左右就已经平滑了，增加样本貌似也解决不了框定位不准的问题，不知道您可有什么建议？谢谢

**Comment by eric612** [comment]
@jijiangyan 
會不會是resize的問題，如果訓練時使用FIT_LARGE_SIZE_AND_PAD ，在inference時請用letterbox resize
反之，使用訓練時使用WARP，在inference時請用WARP resize
@lironghua318 
妳可以修改darknet2caffe.py，基本上是不需要一個輸入的concat，當初寫的比較趕，後來就沒有修正了

**Comment by lironghua318** [comment]
@eric612 好哒，谢谢

**Comment by jijiangyan** [comment]
@eric612 您好，刚刚试了一下yolo_detect.cpp,测试结果和之前一样，还是有偏移，而且都是往左偏，车牌的第七位字符有时都框不到，不知道是什么原因，谢谢您！
![image](https://user-images.githubusercontent.com/25969798/49987554-a1dfef00-ffae-11e8-8549-cdb6e09e3104.png)
![image](https://user-images.githubusercontent.com/25969798/49987562-a60c0c80-ffae-11e8-92b4-c4215c08bd12.png)

**Comment by jijiangyan** [comment]
@eric612 您好，刚刚试了一下yolo_detect.cpp,测试结果和之前一样，还是有偏移，而且都是往左偏，车牌的第七位字符有时都框不到，不知道是什么原因，谢谢您！
![image](https://user-images.githubusercontent.com/25969798/49987767-86291880-ffaf-11e8-863f-321e3fd383c4.png)

**Comment by eric612** [comment]
@jijiangyan 
* yolo loss layer的 thresh 設多少？
如果調高後重新訓練 或許有點幫助
* 使用的model 是 yolo-lite (2 scaless detector) 嗎？如果是的話，試者調成3 scales detector，IOU應該會上升
* k-mean anchors是參照原本的，還是有重算？建議重算anchors會有幫助

**Comment by eric612** [comment]
@jijiangyan 
我找到另外一個原因是，有參數在demo設錯了，因為我一開始用的是1/255 scale，所以一直沿用到錯誤的mean值，導致Bounding box offset有些許偏移，請再更新到最新版。

**Comment by jijiangyan** [comment]
@eric612 您好，之前训练好的模型我用您的方式修改了测试demo，均值为0.5和1的效果几乎差不多，请问训练也需要用您最新的版本进行训练么？

**Comment by eric612** [comment]
據我的測試，只會影響一些offset跟confidence，是不需要重新訓練

**Comment by ersanliqiao** [comment]
> 刚看了论文所以知道可能有这个问题，具体我还没有开始训练呢，后续再交流，还有想问一下prototxt里，这样concat只有一个输入，有啥作用那
> layer {
> bottom: "layer92-conv"
> top: "layer96-route"
> name: "layer96-route"
> type: "Concat"
> }

这层可以删除，应该是darknet模型route层转换时候多的，删除不影响。
