### ISSUE TITLE
F0821 19:12:50.003173 53086 blob.cpp:133] Check failed: data_ 

### ISSUE THREAD

**Issue by wolf345** [eric612/MobileNet-YOLO#4]
I0821 19:12:49.913884 53086 caffe.cpp:255] Starting Optimization
I0821 19:12:49.913894 53086 solver.cpp:302] Solving MobileNet-YOLO
I0821 19:12:49.913898 53086 solver.cpp:303] Learning Rate Policy: multistep
F0821 19:12:50.003173 53086 blob.cpp:133] Check failed: data_ 
*** Check failure stack trace: ***
    @     0x7fd8a2b37daa  (unknown)
    @     0x7fd8a2b37ce4  (unknown)
    @     0x7fd8a2b376e6  (unknown)
    @     0x7fd8a2b3a687  (unknown)
    @     0x7fd8a31089bb  caffe::Blob<>::mutable_cpu_data()
    @     0x7fd8a328b2d9  caffe::RegionLossLayer<>::Forward_cpu()
    @     0x7fd8a30eeb87  caffe::Net<>::ForwardFromTo()
    @     0x7fd8a30eeef7  caffe::Net<>::Forward()
    @     0x7fd8a312afc7  caffe::Solver<>::Step()
    @     0x7fd8a312bd4f  caffe::Solver<>::Solve()
    @           0x40b504  train()
    @           0x407dd8  main
    @     0x7fd8a1acdf45  (unknown)
    @           0x4085b0  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Excuse me, why is this    problem？@eric612

**Comment by Byiie** [comment]
how to fix？
