### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by David-Jin** [eric612/MobileNet-YOLO#41]
/home/king/Documents/MobileNet-YOLO/src/caffe/layers/yolo_detection_output_layer.cpp: In instantiation of ‘void caffe::YoloDetectionOutputLayer<Dtype>::Forward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
/home/king/Documents/MobileNet-YOLO/src/caffe/layers/yolo_detection_output_layer.cpp:353:1:   required from here
/home/king/Documents/MobileNet-YOLO/src/caffe/layers/yolo_detection_output_layer.cpp:261:13: warning: unused variable ‘num’ [-Wunused-variable]
Linking CXX shared library ../../lib/libcaffe.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(object.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe.so.1.0.0] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by macqueen09** [comment]
can you give some more detail? 
after I google , it similar like this :
`https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826365;msg=10`

**Comment by macqueen09** [comment]
can you give some more detail? 
after I google , it similar like this :
[this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826365;msg=10).

**Comment by David-Jin** [comment]
> can you give some more detail?
> after I google , it similar like this :
> [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826365;msg=10).

thank you for your attention, i solved this problem.   i delete the libpython2.7.a lib, and  everything work fine.
