### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by liwanchong** [eric612/MobileNet-YOLO#42]
Hello!
      I get this error when I test it after training with the training instructions you provided.
![image](https://user-images.githubusercontent.com/36127993/50090143-a8869480-0242-11e9-91be-5ffb6d6b0c78.png)
      After viewing the Internet, it is because the deploy.prototxt is not the same as the bias_term setting in train.prototxt.
![image](https://user-images.githubusercontent.com/36127993/50090234-e71c4f00-0242-11e9-8a4a-a724ab05554d.png)
![image](https://user-images.githubusercontent.com/36127993/50090260-f26f7a80-0242-11e9-8df2-e674949ae304.png)
The test picture did not have a picture frame and felt no detection.Also, I found that the mobilenet_yolov3_lite_deploy.caffemodel you provided is 20.8M, and my own caffemodel after training is 21.0M.
      I hope to get your help!
Thank you very much! ! !

**Comment by eric612** [comment]
你指的是[prototxt](https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_deploy.prototxt)與[caffemodel](https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_deploy.caffemodel)嗎

這兩個檔案是經過[merge_bn.py](https://github.com/eric612/MobileNet-YOLO/tree/master/examples/merge_bn)產生出來的，跟你訓練出來的model差在沒有batch norm an scale layer

**Comment by liwanchong** [comment]
您的意思是要把训练出的caffemodel经过merge_bn.py文件处理，还是要在训练之前将train.prototxt和test.prototxt经过merge_bn.py文件处理吗？

**Comment by eric612** [comment]
* 訓練後再處裡就好
* 不處理也可以，將test.prototxt 開頭改成跟deploy.prototxt一樣的data layer，並且去掉DetectionEvaluate layer

**Comment by liwanchong** [comment]
明白了，我先试试，有问题再问您。非常感谢您！！！

**Comment by NJUSTghw** [comment]
hi ,I meet the same issue about the test ,can you  tell me how to solve it?

**Comment by NJUSTghw** [comment]
您好    我通过merge_bn.py处理过了prototxt和caffemodel（训练后的），但是对图像做检测只有图片没有检测框，使用的是example/yolo/detect.py，您知道是什么原因吗？

**Comment by eric612** [comment]
原因可能如下

- 前處理的參數，如mean和scale
- protxt 與 caffemodel 不匹配
- confidence threshold 參數
- ...

可能的原因太多，不勝枚舉，建議一步步釐清

1. 先測試eval test lmdb mAP是否正常
2. 再將test.prototxt 改成deploy測試 detect.py是否正常
3. 最後再用merge_bn將deploy.prototxt合併後測試

**Comment by globalmaster** [comment]
> 您好 我通过merge_bn.py处理过了prototxt和caffemodel（训练后的），但是对图像做检测只有图片没有检测框，使用的是example/yolo/detect.py，您知道是什么原因吗？

你好，我运行python convert_deploy.py VOCself_deploy_iter_17000.caffemodel mobilenet_yolov3_lite_deploy.prototxt  ./**   , python程序并没有改过，但是报错google.protobuf.text_format.ParseError: 2:1 : Expected identifier or number, got .  ，请问你是如何运行成功的？

**Comment by globalmaster** [comment]
> * 訓練後再處裡就好
> * 不處理也可以，將test.prototxt 開頭改成跟deploy.prototxt一樣的data layer，並且去掉DetectionEvaluate layer

你好：
        merge_bn.py处理的是deploy.prototxt 和 caffemodel吗？

**Comment by globalmaster** [comment]
@eric612 @liwanchong

**Comment by Amanda-Barbara** [comment]
@eric612 您好，我这边训练的模型是正常的，我使用convert_deploy.py的时候遇到一些问题，至今没有解决，您能帮我看一下是什么情况吗？谢谢！
python convert_deploy.py ./deploy_test_pruned.prototxt ./snapshot/yolo_lite_pruned_head_1018_iter_41000.caffemodel 1023
there have a bug like this:
merge_bn/remove_bn.py", line 34, in remove_bn_prototxt
    net.layer[idx].param[0].lr_mult = int(1)
IndexError: list index out of range

I

**Comment by eric612** [comment]
@Amanda-Barbara 
我不確定是什麼問題，不過我看我local的repo跟git上的不太一樣，所以更新了一版，你再試試

**Comment by Amanda-Barbara** [comment]
![image](https://user-images.githubusercontent.com/38062165/67364556-5ae56180-f5a2-11e9-9946-48d18632b82e.png)
您好，这是我是用带bn的deploy配置文件测试的结果，您刚刚更新的repo我这边可以转成功，但是没有检测到人头，我使用ncnn转的模型也是没有检测到人头，还有其他原因吗？谢谢您的帮忙！

**Comment by zpge** [comment]
> 您好 我通过merge_bn.py处理过了prototxt和caffemodel（训练后的），但是对图像做检测只有图片没有检测框，使用的是example/yolo/detect.py，您知道是什么原因吗？

你好，你的问题解决了吗？我遇到了一样的问题。mobilenetv2-yolov3-lite剪枝过的模型训练后检测图片可以检测到目标，但是merge_bn后检测不到。用的另外一个模型mobilenet-yolov3是可以的，所以觉得很奇怪。

**Comment by eric612** [comment]
@zpge 
這兩種merge bn 你可以試試看，我已經忘記是哪個才能正確轉換

https://github.com/Robert-JunWang/Pelee/blob/master/tools/gen_merged_model.py

https://github.com/eric612/MobileNet-YOLO/tree/master/examples/merge_bn

**Comment by zpge** [comment]
> @zpge
> 這兩種merge bn 你可以試試看，我已經忘記是哪個才能正確轉換
> 
> https://github.com/Robert-JunWang/Pelee/blob/master/tools/gen_merged_model.py
> 
> https://github.com/eric612/MobileNet-YOLO/tree/master/examples/merge_bn

感谢回复，第一个方案在mobilenetv2-yolov3-lite上成功了。
第二个在mobilenet-yolov3上成功了，还是要回去仔细看下代码

**Comment by xiaoping2015** [comment]
> > @zpge
> > 這兩種merge bn 你可以試試看，我已經忘記是哪個才能正確轉換
> > https://github.com/Robert-JunWang/Pelee/blob/master/tools/gen_merged_model.py
> > https://github.com/eric612/MobileNet-YOLO/tree/master/examples/merge_bn
> 
> 感谢回复，第一个方案在mobilenetv2-yolov3-lite上成功了。
> 第二个在mobilenet-yolov3上成功了，还是要回去仔细看下代码

请问你第二个是怎么实现的？
