### ISSUE TITLE
something about pretrained caffemodel

### ISSUE THREAD

**Issue by jijiangyan** [eric612/MobileNet-YOLO#44]
hello, I see you used mobilenet_yolov3_lite_coco.caffemodel as your pretrained caffemodel. If you mind upload this caffemodel? By the way, I want to know mobilenet_yolov3_lite_coco.caffemodel and mobilenet_iter_73000.caffemodel  are trained from what dataset. Thank you very much!

**Comment by eric612** [comment]
You can find "Download pre-trained weights, and save at $caffe_root\models\MobileNet" in wiki home. 

https://drive.google.com/open?id=1Xd_Baq1fbjNne_1DAJnR3-RoZ73x4QX_

**Comment by jijiangyan** [comment]
thank you very much！
