### ISSUE TITLE
TensorRT implementation

### ISSUE THREAD

**Issue by shiva13425** [eric612/MobileNet-YOLO#45]
Is there a possibility to implement TensorRT.

**Comment by eric612** [comment]
Due to your [issue](https://github.com/lewes6369/tensorRTWrapper/issues/1), I think error message just told you can't not use negative slope , so you can just remove negative slope from relu layer (recommend retrain on my caffe) , and then try it again

**Comment by shiva13425** [comment]
@eric612 have you tried with TensorRT implementation on mobilenet_yolov3_lite.

**Comment by eric612** [comment]
No , I didn't try it yet , Unfortunately , now my first priority was semantic segmentation combination , so maybe one day I will test it

**Comment by shiva13425** [comment]
@eric612 Sure. Thanks for your great work.
