### ISSUE TITLE
How to train MobileNet-YOLO-v3-lite with custom dataset?

### ISSUE THREAD

**Issue by PiyalGeorge** [eric612/MobileNet-YOLO#47]
Hi, @eric612 , Thanks for this amazing repo. Your [mobilenet-yolov3-lite model](https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_deploy.caffemodel) is giving good results with good fps. 
Currently following your repo, i'm trying to do training on mobilenet-yolov3-lite with my custom dataset. I'm having 6 classes(including background), 50000 images converted to LMDB. I'm using [train_yolov3_lite.sh](https://github.com/eric612/MobileNet-YOLO/blob/master/train_yolov3_lite.sh) for training. I modified _mobilenet_yolov3_lite_train.prototxt_, label_prototxt, LMDB and batch_size in [here](https://raw.githubusercontent.com/eric612/MobileNet-YOLO/master/models/yolov3/mobilenet_yolov3_lite_train.prototxt). My system allows a batch size of only 2 for training and 1 for testing(total 3). I have trained till 50000 iterations. I modified the classes in _yolo_detect.cpp_ , make file, etc. then modified the _demo_yolo_lite.sh_ for the new model. but it caused some convolution 'bias_term' issue in _mobilenet_yolov3_lite_deploy.prototxt_ . Hence modified that deploy file also. After rectifying all these, when i try to run the model, it still doesn't give output, no errors. Can you help me resolve this?

**Comment by eric612** [comment]
mobilenet_yolov3_lite_deploy.prototxt was mad from merge_bn.py , you can't use it directly. 

I suggest you can try modify test.prototxt to deploy.prototxt first (replace data layer and remove eval. layer)

**Comment by PiyalGeorge** [comment]
Thanks @eric612 , I'll try that. 
Also while training, do i need to change 'num_class', or 'num' anywhere in _mobilenet_yolov3_lite_train.prototxt_  or in _test.prototxt_ based on number of classes i'm training? 

In the last lines -
 
yolov3_param {
      side: 26
    num_class: 20
    num: 3
    ......
}

**Comment by eric612** [comment]
See issue [#12](https://github.com/eric612/MobileNet-YOLO/issues/12)

**Comment by globalmaster** [comment]
> Hi, @eric612 , Thanks for this amazing repo. Your [mobilenet-yolov3-lite model](https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_deploy.caffemodel) is giving good results with good fps.
> Currently following your repo, i'm trying to do training on mobilenet-yolov3-lite with my custom dataset. I'm having 6 classes(including background), 50000 images converted to LMDB. I'm using [train_yolov3_lite.sh](https://github.com/eric612/MobileNet-YOLO/blob/master/train_yolov3_lite.sh) for training. I modified _mobilenet_yolov3_lite_train.prototxt_, label_prototxt, LMDB and batch_size in [here](https://raw.githubusercontent.com/eric612/MobileNet-YOLO/master/models/yolov3/mobilenet_yolov3_lite_train.prototxt). My system allows a batch size of only 2 for training and 1 for testing(total 3). I have trained till 50000 iterations. I modified the classes in _yolo_detect.cpp_ , make file, etc. then modified the _demo_yolo_lite.sh_ for the new model. but it caused some convolution 'bias_term' issue in _mobilenet_yolov3_lite_deploy.prototxt_ . Hence modified that deploy file also. After rectifying all these, when i try to run the model, it still doesn't give output, no errors. Can you help me resolve this?

Hi,

Have you solved this problem? Now I'm training on my own dataset and I'm facing the same problem with you. Can you help me resolve this? 

Thanks

**Comment by PiyalGeorge** [comment]
Hi @eric612 , Extremely sorry for late reply. Thanks alot, your above mentioned methods works perfectly for custom training and detection. Thanks :blush: :smiley:

**Comment by PiyalGeorge** [comment]
Hi @globalmaster , Sorry for the late reply. 
Actually all your answers is mentioned by @eric612 , in the above comments. Anyway i'll join all comments and here is what you want:
Hope you have LMDB database of custom dataset with specific classes. I'll explain how i've done with 5 classes(excluding background). For example i have 5 classes(person, dog, cat, car, bus).

In **mobilenet_yolov3_lite_train.prototxt**, modify:
- lmdb file path
- label_map.prototxt
- Modify 'num_output: 75' in the file as follows:-
  the above 75 was obtained from the calculation (5+classno)*3, where classno is the number of classes(without considering background in the count), and here eric's classno is 20.
  So if you have 5 classes(for eg:- person, dog, cat, car, bus), then the value is (5+5)*3=30, so modify 'num_output: 75' in file to 'num_output: 30'.
- Search for 'num_class: 20' in the file and modify the value as follows:-
  if you have 5 classes(for eg:- person, dog, cat, car, bus), then modify the value into 'num_class: 5'

In **mobilenet_yolov3_lite_test.prototxt**, modify:

- lmdb file path
- label_map.prototxt
- Modify 'num_output: 75' in the file as follows:-
  the above 75 was obtained from the calculation (5+classno)*3, where classno is the number of classes(without considering background in the count), and here eric's classno is 20.
  So if you have 5 classes(for eg:- person, dog, cat, car, bus), then the value is (5+5)*3=30, so modify 'num_output: 75' in file to 'num_output: 30'.
- Modify 'num_classes: 20' to 'num_classes: 5'
- Modify 'num_classes: 21' to 'num_classes: 6'

Once Training is done:
Modify the MobileNet-YOLO/examples/yolo/**yolo_detect.cpp**. You need to modify line:
char* CLASSES[21] = { "__background__", ....., "train", "tvmonitor" };
with classes.

Then once again run make commands:

> cd build
> cmake ..
> make -j4
> make pycaffe

Now modify MobileNet-YOLO/**demo_yolo_lite.sh** . Just now the eric has uploaded new mobilenet_yolov3_lite_deploy.prototxt , https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_bn_deploy.prototxt . 

In mobilenet_yolov3_lite_bn_deploy.prototxt, modify:-

- Modify 'num_output: 75' in file to 'num_output: 30' following above same criterias
- Modify 'num_classes: 20' to 'num_classes: 5'

Thank you

**Comment by TianSong1991** [comment]
> Hi @globalmaster , Sorry for the late reply.
> Actually all your answers is mentioned by @eric612 , in the above comments. Anyway i'll join all comments and here is what you want:
> Hope you have LMDB database of custom dataset with specific classes. I'll explain how i've done with 5 classes(excluding background). For example i have 5 classes(person, dog, cat, car, bus).
> 
> In **mobilenet_yolov3_lite_train.prototxt**, modify:
> 
> * lmdb file path
> * label_map.prototxt
> * Modify 'num_output: 75' in the file as follows:-
>   the above 75 was obtained from the calculation (5+classno)*3, where classno is the number of classes(without considering background in the count), and here eric's classno is 20.
>   So if you have 5 classes(for eg:- person, dog, cat, car, bus), then the value is (5+5)*3=30, so modify 'num_output: 75' in file to 'num_output: 30'.
> * Search for 'num_class: 20' in the file and modify the value as follows:-
>   if you have 5 classes(for eg:- person, dog, cat, car, bus), then modify the value into 'num_class: 5'
> 
> In **mobilenet_yolov3_lite_test.prototxt**, modify:
> 
> * lmdb file path
> * label_map.prototxt
> * Modify 'num_output: 75' in the file as follows:-
>   the above 75 was obtained from the calculation (5+classno)*3, where classno is the number of classes(without considering background in the count), and here eric's classno is 20.
>   So if you have 5 classes(for eg:- person, dog, cat, car, bus), then the value is (5+5)*3=30, so modify 'num_output: 75' in file to 'num_output: 30'.
> * Modify 'num_classes: 20' to 'num_classes: 5'
> * Modify 'num_classes: 21' to 'num_classes: 6'
> 
> Once Training is done:
> Modify the MobileNet-YOLO/examples/yolo/**yolo_detect.cpp**. You need to modify line:
> char* CLASSES[21] = { "**background**", ....., "train", "tvmonitor" };
> with classes.
> 
> Then once again run make commands:
> 
> > cd build
> > cmake ..
> > make -j4
> > make pycaffe
> 
> Now modify MobileNet-YOLO/**demo_yolo_lite.sh** . Just now the eric has uploaded new mobilenet_yolov3_lite_deploy.prototxt , https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_bn_deploy.prototxt .
> 
> In **mobilenet_yolov3_lite_bn_deploy.prototxt**, modify:-
> 
> * Modify 'num_output: 75' in file to 'num_output: 30' following above same criterias
> * Modify 'num_classes: 20' to 'num_classes: 5'
> 
> Now go ahead and run the command bash demo_yolo_lite.sh
> Thank you, Hope this helps you

@PiyalGeorge 
Hi PiyalGeorge, I follow your steps and run `sh train_yolov3_lite_self.sh`  and finally I obtain the caffe model.But when I run `python merge_bn.py --model example/mobilenet_yolov3_lite_solver.prototxt --weights snapshot/mydata_deploy_iter_20000.caffemodel` 
It makes run and the feedback as follow:

> Traceback (most recent call last):
>   File "merge_bn.py", line 60, in <module>
>     net_deploy = caffe.Net(deploy_proto, caffe.TEST)  
> RuntimeError: Could not open file /media/pico/data2/kevin/MobileNet-YOLO/data/VOCself/remove_bn.prototxt

Should I create the remove_bn.prototxt first?

**Comment by PiyalGeorge** [comment]
Hi @TianSong1991 , haven't you checked eric's latest update? i updated the repo today. There is no need for you to run merge_bn.py, since he has already gave you the file directly. This is the new file eric has added - https://github.com/eric612/MobileNet-YOLO/blob/master/models/yolov3/mobilenet_yolov3_lite_bn_deploy.prototxt . 

In mobilenet_yolov3_lite_bn_deploy.prototxt, you need to modify as i specified above.
You also need to modify command in demo_yolo_lite.sh, with mobilenet_yolov3_lite_bn_deploy.prototxt

**Comment by TianSong1991** [comment]
Oh thank you very much! @PiyalGeorge

**Comment by shuxiao9058** [comment]
> * the above 75 was obtained from the calculation (5+classno)*3, where classno is the number of classes(without considering background in the count), and here eric's classno is 20.

@PiyalGeorge 
all the 75 in the train file need modify?

**Comment by PiyalGeorge** [comment]
> > * the above 75 was obtained from the calculation (5+classno)*3, where classno is the number of classes(without considering background in the count), and here eric's classno is 20.
> 
> @PiyalGeorge
> all the 75 in the train file need modify?

Bro, Yes. Above it specifies to Modify 'num_output: 75' in the file. so search for 'num_output: 75' in the file and modify that only. :smiley: :smiley:
