### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by macqueen09** [eric612/MobileNet-YOLO#48]
Ubuntu14
Cuda=10.0
cudnn=7.4.1
GPU=1080Ti
OpenCV = 3.4.0
when I cmake this project in a new computer , it occured:
` CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /media/py/000E741100097EE8/mkl/MobileNet-YOLO/src/caffe
-- Configuring incomplete, errors occurred! `

我怀疑是cuda版本过高导致caffe不兼容。
这个错误在stackoverflow上也并没有得到解答，所以问一下你和其他看到帖子的人，是否能帮忙解决这个编译错误，Thanks  very much

**Comment by macqueen09** [comment]
file:///media/py/000E741100097EE8/mkl/docu/cudacublas_device_library%20-%20%E5%89%AF%E6%9C%AC.jpeg

**Comment by macqueen09** [comment]
![cudacublas_device_library -](https://user-images.githubusercontent.com/16522286/50449122-242dc300-0960-11e9-9514-183743c0e80c.png)

**Comment by macqueen09** [comment]
I have change cudnn = disable
to 
cudnn = 7.4.1
but still has this problem

**Comment by eric612** [comment]
You can try use OpenCV 3.3.1 first

**Comment by 72ll** [comment]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /home/rk/MobileNet-YOLO-master/src/caffe

I have the same problem on JetsonNano, how can I solve it ?
Looking forward to your response...
