### ISSUE TITLE
计算模型的mAP

### ISSUE THREAD

**Issue by YiDing2333** [eric612/MobileNet-YOLO#49]
您好，请问如何计算模型的mAP，我看了#26，但还是不清楚具体该怎么操作

**Comment by eric612** [comment]
根據我的solver設定，mAP在caffe訓練過程中，每一千筆會測試一次mAP，你只要下指令訓練即可

**Comment by YiDing2333** [comment]
我的训练没有问题，但是在训练中每次测试时detection_eval都等于0，不知道是哪里有问题，麻烦您帮我看一下
这是训练过程中的log记录，输出测试的结果
![default](https://user-images.githubusercontent.com/27810038/50676671-88bbe280-1030-11e9-8f80-7d408c3e3365.JPG)
这是我solver中的内容
![default](https://user-images.githubusercontent.com/27810038/50676724-dd5f5d80-1030-11e9-81c0-74e02e072e9a.JPG)
这是test中配置数据的部分
![default](https://user-images.githubusercontent.com/27810038/50676779-2d3e2480-1031-11e9-96ba-9824ab81bddd.JPG)

**Comment by eric612** [comment]
方便將prototxt 與 training log 上傳嗎，這樣看會比較快

**Comment by YiDing2333** [comment]
非常感谢
[mobilenetv1_yolov3_coco.zip](https://github.com/eric612/MobileNet-YOLO/files/2726887/mobilenetv1_yolov3_coco.zip)
[train-2018-12-15-19-16-47.zip](https://github.com/eric612/MobileNet-YOLO/files/2726888/train-2018-12-15-19-16-47.zip)

**Comment by eric612** [comment]
- 我發現你將depthwise convolution加上 shortcut ，類似的結構我有試過mobilenetv2 ，但精準度不是很好，同樣的問題mobilenetv2-ssdlite也會遇到，建議不要使用此類結構

- 另外將backbone網路修改後，如果沒有相對應的pretrained weights，也會造成精準度下降

**Comment by YiDing2333** [comment]
谢谢，我再认真修改一下我的网络结构
不知道我的prototxt在您那运行时，测试的detection_eval是否为0，是配置的有问题还是有别的什么问题

**Comment by YiDing2333** [comment]
才发现测试集是没有标注的 验证集里才有标注 换成coco的验证集就好了
