### ISSUE TITLE
在自己处理过的数据上训练效果很差

### ISSUE THREAD

**Issue by globalmaster** [eric612/MobileNet-YOLO#50]
你好：
         我对VOC数据集进行了处理，处理过后共有5类，分别是person、bicycle、car、motorbike、bus。用
mobilenet_yolov3_lite进行训练。我已經修改了对应的train.prototxt、test.prototxt、solver.prototxt。训练过程中看着输出的参数也基本正常，但是最终进行预测的时候效果很差。设置的阈值低的话，满屏都是框；设置的阈值高的话，就根本检测不出来。请问这是什么原因？如何能够解决这个问题？谢谢！

**Comment by globalmaster** [comment]
我是把模型和deploy.prototxt转为ncnn的模型，在手机上运行时出现的上面的问题。

在电脑上运行时问题如下：
I0104 10:36:12.538003 10501 net.cpp:744] Ignoring source layer label_data_1_split
F0104 10:36:12.538015 10501 net.cpp:750] Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv0
*** Check failure stack trace: ***
    @     0x7f14f31d75cd  google::LogMessage::Fail()
    @     0x7f14f31d9433  google::LogMessage::SendToLog()
    @     0x7f14f31d715b  google::LogMessage::Flush()
    @     0x7f14f31d9e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f14f392c65b  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7f14f3933aa5  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f14f3933b87  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40d4fb  Detector::Detector()
    @           0x406172  main
    @     0x7f14eccfa830  __libc_start_main
    @           0x407c29  _start
    @              (nil)  (unknown)
Aborted (core dumped)
请问我该如何解决？

**Comment by globalmaster** [comment]
@eric612

**Comment by eric612** [comment]
你可能必須先確認一些前處理的問題

- VOC 5 類 ，有[正確修改](https://github.com/eric612/MobileNet-YOLO/blob/master/data/VOC0712/labelmap_voc.prototxt)

- train and test protxt 有正確修改classes and channel

- 測試validation mAP是否正常，最後才是測試圖片

**Comment by globalmaster** [comment]
> 你可能必須先確認一些前處理的問題
> 
> * VOC 5 類 ，有[正確修改](https://github.com/eric612/MobileNet-YOLO/blob/master/data/VOC0712/labelmap_voc.prototxt)
> * train and test protxt 有正確修改classes and channel
> * 測試validation mAP是否正常，最後才是測試圖片

你好：
运行merge_bn.py 是处理train.prototxt还是deploy.prototxt? 我处理了deploy.prototxt，并根据提示，将一些bias_term改为 fslae,可以转化成功，但是检测图片的时候确检测不到物体，confidence设为0也不行。请问这个问题如何解决？

**Comment by eric612** [comment]
除了bias_term改为 false ，還要將batch norm layer 與 scale layer移除才是正確的流程

**Comment by eric612** [comment]
不好意思，上一篇沒注意到直接剪貼，正確的流程是將conv layer的bias_term改為true ，接者把conv後的scale 與batch norm 移除，在使用merge_bn.py ，如果你覺得前述流程不方便使用，可以使用我的merge_bn.py ，會自動產生新的prototxt，而不用手動修改

**Comment by globalmaster** [comment]
> 不好意思，上一篇沒注意到直接剪貼，正確的流程是將conv layer的bias_term改為true ，接者把conv後的scale 與batch norm 移除，再使用merge_bn.py ，如果你覺得前述流程不方便使用，可以使用我的merge_bn.py ，會自動產生新的prototxt，而不用手動修改

你好：
我还是没有运行成功，可以加个微信详细请教一下吗？ 我的微信是18811526686。

**Comment by globalmaster** [comment]
> 不好意思，上一篇沒注意到直接剪貼，正確的流程是將conv layer的bias_term改為true ，接者把conv後的scale 與batch norm 移除，再使用merge_bn.py ，如果你覺得前述流程不方便使用，可以使用我的merge_bn.py ，會自動產生新的prototxt，而不用手動修改

你好：
请问到底是修改train.prototxt还是修改deploy.prototxt？
我该怎么运行你的merge_bn.py？我运行了它会报错

**Comment by eric612** [comment]
如果很難理解的話，建議先從這個專案開始練習
https://github.com/NHZlX/Merge_bn_Caffe

接者開始試者練習mobilenet-ssd ，那邊也有類似的問題，但可找到的資料較多

**Comment by eric612** [comment]
Far away topic
