### ISSUE TITLE
YOLOv3-mobilenet in darknet 

### ISSUE THREAD

**Issue by Lynnee123** [eric612/MobileNet-YOLO#52]
Thank you so much for your sharing.have you  realize the yolov3-mobilenet version on the darknet framework?How about the comparison between these two versions.  if you have , could you provide me the files of.cfg and.weigth?.Thank you very much

**Comment by eric612** [comment]
You can see below issues from AlexeyAB project ,

https://github.com/AlexeyAB/darknet/issues/2050
https://github.com/AlexeyAB/darknet/issues/1684
https://github.com/AlexeyAB/darknet/issues/2005
