### ISSUE TITLE
normalize_value 值对forward时间的影响

### ISSUE THREAD

**Issue by wzj5133329** [eric612/MobileNet-YOLO#72]
我测试yolo_detect.cpp时发现normalize_value值对检测效果以及net->forward时间影响特别大，我只知道这个值在图片转为矩阵时有影响，却不知道具体什么意思，能帮助解答一下吗？谢谢

**Comment by eric612** [comment]
Normalize value會影響值域，簡單來說，如果只單看信心值，有時會造成總體有個偏移量(offset)，造成過多的檢測框或是完全沒有檢測框，此時前者的yolo detection output layer會過度耗費時間 (要算bbox和nms)，當然yolo detection output layer目前沒有最佳化也有一些關係，你可以自己實驗看看

**Comment by wzj5133329** [comment]
感谢解惑，我将再去查看yolo detection output layer代码。。。

**Comment by eric612** [comment]
另外，一般我不推薦Caffe當作inference端的工具，所以如果想要追求最佳的速度，建議是找一個Edge端的framework來改，如ncnn或是tersorRT。

**Comment by wzj5133329** [comment]
好的，我将试试别的推理框架，非常感谢。。。
