### ISSUE TITLE
 About train_yolo_lite.sh

### ISSUE THREAD

**Issue by grainw** [eric612/MobileNet-YOLO#8]
Hi @eric612 thanks for the great project. when I use tain_yolo_lite.sh , I got the error
I0828 10:55:39.278422 11427 blocking_queue.cpp:50] Data layer prefetch queue empty
F0828 10:55:40.675819 11427 blob.cpp:133] Check failed: data_ 
*** Check failure stack trace: ***
can you tell me why? Thank you

**Comment by eric612** [comment]
Please check the path exist "$caffe_root\examples\VOC0712\VOC0712_trainval_lmdb" and "$caffe_root\examples\VOC0712\VOC0712_test_lmdb"

**Comment by grainw** [comment]
The same path , train_yolov3_lite.sh is ok.

**Comment by eric612** [comment]
I fixed the bug , thanks your feedback
