### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_75'

### ISSUE THREAD

**Issue by CalvinPaean** [eric612/MobileNet-YOLO#86]
Hi Eric,

Thanks for your work. I have an error when compiling this project.
Could you please help me to solve it? I'll appreciate it a lot.
My GPU is 2080ti and CUDA is 9.0.
nvcc fatal   : Unsupported gpu architecture 'compute_75'
CMake Error at cuda_compile_generated_pooling_layer.cu.o.cmake:207 (message):
  Error generating
  /home/goldenridge/MobileNet-YOLO/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_pooling_layer.cu.o

**Comment by biankaikai** [comment]
I have solved this issue. I changed the Cuda.cmake file in Cmake folder. 
Change the following line 
set(Caffe_known_gpu_archs "30 35 50 52 61")
Then, when using cmake, try " cmake -DCUDA_ARCH_NAME=All"

**Comment by CalvinPaean** [comment]
I have solved this issue. I changed the Cuda.cmake file in Cmake folder.

Change the following line

set(Caffe_known_gpu_archs "30 35 50 52 61")

Then, when using cmake, try "cmake -DCUDA_ARCH_NAME=All"
