### ISSUE TITLE
always show waitting for data

### ISSUE THREAD

**Issue by wzj5133329** [eric612/MobileNet-YOLO#88]
你好，当我用VOC2007 和2012制作数据集后，训练时，一直显示waitting for data,你知道时为什么吗？昨天晚上几个小时都是这样，
I0321 09:30:11.377269  4039 net.cpp:257] Network initialization done.
I0321 09:30:11.377630  4039 solver.cpp:70] Solver scaffolding done.
I0321 09:30:11.412041  4039 caffe.cpp:239] Starting Optimization
I0321 09:30:11.412057  4039 solver.cpp:302] Solving 
I0321 09:30:11.412076  4039 solver.cpp:303] Learning Rate Policy: multistep
I0321 09:30:11.421068  4039 blocking_queue.cpp:50] Waiting for data

**Comment by wzj5133329** [comment]
我找到原因了，在编译完成后，因为出错 math_functions.cpp:276] Check failed: a <= b  ,我将math_functions.cpp中的CHECK_LE(a,b)注释掉了 ，这样简单注释掉后会造成队列空，
修改 caffe_rng_uniform函数为
 void caffe_rng_uniform(const int n,  Dtype a,  Dtype b, Dtype* r) {
  CHECK_GE(n, 0);
  CHECK(r);
  //CHECK_LE(a, b);

  /////更改//////
  if(a > b) {
    Dtype c = a;
    a = b;
    b = c;
  }
  CHECK_LE(a, b);
...

**Comment by hufangjian** [comment]
多等会就好了，我这边差不多大半个小时左右。

**Comment by eric612** [comment]
https://github.com/eric612/MobileNet-YOLO/issues/117
