### ISSUE TITLE
 error: function "caffe::Yolov3DetectionOutputLayer<Dtype>::Backward_gpu" has already been defined

### ISSUE THREAD

**Issue by unlabeledData** [eric612/MobileNet-YOLO#89]
Do you know this error?
Can I remove yolov3_detection_output_layer.cu when I ues GPU for training YOLO-v3?

/home/user/MobileNet-YOLO/src/caffe/layers/yolov3_detection_output_layer.cu(79): error: function "caffe::Yolov3DetectionOutputLayer<Dtype>::Backward_gpu" has already been defined

1 error detected in the compilation of "/tmp/tmpxft_00000284_00000000-7_yolov3_detection_output_layer.cpp1.ii".
CMake Error at cuda_compile_1_generated_yolov3_detection_output_layer.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/user/MobileNet-YOLO/build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_yolov3_detection_output_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_yolov3_detection_output_layer.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by eric612** [comment]
I looks like my last commit cause , can you help me to try it on previous version

**Comment by unlabeledData** [comment]
I tried last version you committed at Jan, 24. The error happened again.

**Comment by nanditam1** [comment]
Hi, thanks for sharing your work!!  I too am stuck with same issue, 

error: function "caffe::Yolov3DetectionOutputLayer<Dtype>::Backward_gpu" has already been defined

 CMake Error at cuda_compile_generated_yolov3_detection_output_layer.cu.o.cmake:266 (message):Error generating file MobileNet-YOLO/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_yolov3_detection_output_layer.cu.o

Any suggestions on how to debug this? Thanks

**Comment by eric612** [comment]
Sorry , I check my local repo , and I missed upload some code. I just commit a new version

**Comment by nanditam1** [comment]
I have tried new commit, the same error is popping up again : 
/MobileNet-YOLO/src/caffe/layers/yolov3_detection_output_layer.cu(79): error: function "caffe::Yolov3DetectionOutputLayer<Dtype>::Backward_gpu" has already been defined

1 error detected in the compilation of "/tmp/tmpxft_00007941_00000000-6_yolov3_detection_output_layer.cpp1.ii".
CMake Error at cuda_compile_generated_yolov3_detection_output_layer.cu.o.cmake:266 (message):
  Error generating file
  /datadrive/newcommit_mobilenet_yolo/MobileNet-YOLO/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_yolov3_detection_output_layer.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:224: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_yolov3_detection_output_layer.cu.o' failed

Looks like some other issue? thanks

**Comment by nanditam1** [comment]
Yes now it is building successfully. thanks

**Comment by unlabeledData** [comment]
Thank you very much. I successfully build it.
What's more, do you have the pretrain model of YOLO-v3 on caffe? The backbone is Darknet-53?

**Comment by eric612** [comment]
No , I always use pytorch converter to transfer model from darknet to caffe , and retrain on this project 
https://github.com/eric612/MobileNet-YOLO/tree/master/models/darknet_yolov3
