### ISSUE TITLE
About taining in my own data

### ISSUE THREAD

**Issue by grainw** [eric612/MobileNet-YOLO#9]
Hi @eric612 thanks for the great project. I set solver_mode is GPU. When i use the VOC data to train it is fast ,but when i use my own data to train is  very slowly.  My own image's size is 1920 * 1080. My GPU Memory-Usage is 5000M ,but my GPU-Util is always 0%, sometime will be 80%.  Can you tell me why and how i can solve it ?

**Comment by eric612** [comment]
I guess the reason was the resize function, you can try to resize image when produce lmdb , set the resize width and height at "create_annoset.py" (larger than 608 was suggestion)

**Comment by grainw** [comment]
@eric612 Thanks for you answer. I change the size  in create_data.sh ,the speed is faster . I want to know whether the label will make a mistake.

**Comment by eric612** [comment]
[ssd caffe](https://github.com/weiliu89/caffe/issues/584#issuecomment-302444673)
You can try to optimize code or use python code to resize image and xml beforce create lmdb
