### ISSUE TITLE
I'm going to find a dataset which include bounding box , segmentation and lane annotation data

### ISSUE THREAD

**Issue by eric612** [eric612/MobileNet-YOLO#90]
If you know where can download , please tell me

**Comment by guan-yuan** [comment]
BDD100K: A Large-scale Diverse Driving Video Database (https://bair.berkeley.edu/blog/2018/05/30/bdd/)

**Comment by eric612** [comment]
* It is very helpful for me , thanks a lots . 
* I will update if I have any results

**Comment by eric612** [comment]
Hi , 
I have start to train bdd100k , current progress was at tiers 30k (I set 180k iters total) , the results looks good , below is the video

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/iwiYUFAW0EA/0.jpg)](https://www.youtube.com/watch?v=iwiYUFAW0EA)
