### ISSUE TITLE
How to calculate anchors

### ISSUE THREAD

**Issue by embedeepLHY** [eric612/MobileNet-YOLO#92]
I run the python scripts in wiki "Generate anchors to increase performance" with VOC datasets,  but get different results with the data in mobilenet_yolov3_train.prototxt 
our results : " 1.17,1.86, 2.08,5.01, 4.38,3.67, 4.51,8.81, 8.96,6.06, 10.29,11.00 ". mobilenet_yolov3_train.prototxt: "10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326"
So, what am I missing?

**Comment by eric612** [comment]
Did your python code set width and height to 416 ? like [this](https://github.com/AlexeyAB/darknet/blob/master/scripts/gen_anchors.py)

**Comment by embedeepLHY** [comment]
Yes, i used [voc_label.py](https://github.com/AlexeyAB/darknet/blob/master/scripts/voc_label.py) to generate train.txt , and [gen_anchors.py](https://github.com/AlexeyAB/darknet/blob/master/scripts/gen_anchors.py)  to generate anchors6.txt, and get 1.17,1.89, 2.09,5.06, 4.36,3.70, 4.52,8.85, 8.89,6.06, 10.30,10.96, 0.635962

**Comment by embedeepLHY** [comment]
By the way, we use both the train.txt and train.all.txt, and get the almost same results

**Comment by eric612** [comment]
It is very strange , can you try this [way](https://github.com/AlexeyAB/darknet/issues/1517)

**Comment by embedeepLHY** [comment]
We will try it just now. Thanks!

**Comment by embedeepLHY** [comment]
Hi~ eric，we have run “./darknet detector calc_anchors data/voc.data -num_of_clusters 6 -width 416 -height 416” as your suggestion, and get a more reasonable anchors results as follow : "anchors =  34, 62,  87,110,  93,227, 246,163, 179,307, 345,337; avg IoU = 63.61 %", we using both VOC2007 and VOC2012. 
Then, we realize that the darknet using a c implementation to calc anchors instead of the python scripts, so, maybe we can conclude that the python scripts [here](https://github.com/AlexeyAB/darknet/blob/master/scripts/gen_anchors.py) is unavailable?

**Comment by eric612** [comment]
Greats , thanks for your feedback

**Comment by embedeepLHY** [comment]
Thanks for your sharing, your excellent work inspire us a lot!
