### ISSUE TITLE
[Training Issue] reproduce yolov3 coco

### ISSUE THREAD

**Issue by ryusaeba** [eric612/MobileNet-YOLO#99]
Model : yolov3
Backbone : mobilenet
Questions :
Hi @eric612 ,
I would like to reproduce below highlighted result by using initial training.
![image](https://user-images.githubusercontent.com/29192565/56412853-16f26680-62b8-11e9-88ca-a6cda1f02530.png)

When you are available, please give me some suggestions if I am wrong. 
1. Based on pretrained model (\MobileNet\mobilenet_iter_73000.caffemodel)
2. Use the following files in [here](https://github.com/eric612/MobileNet-YOLO/tree/master/models/yolov3_coco), including
mobilenet_yolov3_solver.prototxt
mobilenet_yolov3_test.prototxt
mobilenet_yolov3_train.prototxt

Then I should be able to get the similar results as yours, correct?
If the solver is not correct one, could you please share the correct one with me?

Thanks

**Comment by eric612** [comment]
Yes , all is correct , but the model was trained from my previous version caffe , so I'm not sure you can get the same mAP

**Comment by ryusaeba** [comment]
@eric612 
Thanks for the confirmation. I think the mAP difference expected because data argumentation is random. It is hard to get exactly the same mAP.
